### ISSUE TITLE
{Update} add load list-ip.txt

### ISSUE THREAD

**Issue by lolminerxmrig** [MustafaOmidian/Auto-rdp-cracker#3]
Hi.
plz add load list-ip.txt
my list ip: 
ip:port
or
ip

**Comment by MustafaOmidian** [comment]
https://www.ipdeny.com/ipblocks/data/aggregated/us-aggregated.zone

**Comment by MustafaOmidian** [comment]
you can download retrieve IP list  from this ipdeny.com.
im gonna update code until next week stay intouch

**Comment by lolminerxmrig** [comment]
my list ip censys.io all rdp work but need only list load
