### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by sec13b** [MustafaOmidian/Auto-rdp-cracker#4]
[WARNING] rdp servers often don't like many connections, use -t 1 or -t 4 to reduce the number of parallel connections and -W 1 or -W 3 to wait between connection to allow the server to recover
[INFO] Reduced number of tasks to 4 (rdp does not like many parallel connections)
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task

how to fix for better results.

Thank you

**Comment by nicthenothing** [comment]
thank you.
i updated the code
